# Generated by Django 4.2.20 on 2025-03-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vintage_cars_app', '0002_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='purchasers',
        ),
    ]
